rvm:
- 2.6.3
before_install:
- gem install bundler
cache: bundler
script: bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: p3K5StUor2RSx0ofbLyh5Rsi8TcbfEWpAt8h++3BdY+uIMHQuGRu2r8+nF8JSxwNjlyj+F/FiU2p0yI2r8xpcy3/1X7PwzI8/sOv7YHQlzSTeEli2NB41gXc0FRZz5ORALU3BXF4CdSyruuoRrz+YQoNfrp0xkQ+t3BEiE0L/JIv6RhgCcyUTb+/4CUfhIXyqQYlDN6WKMGzgbY8dJsAs/O0aSy3DzKfcAETx7vxXP8TsBv4BHALKOiRFdbx5V0vlmaJ6BgBGDbg9geeEBdstmttSVh2M5gm9T6ftfBVBvBCDhVejmowMqp5g4HytyiYzUt4j2AfD5qnx5g9eA+LSKzmvMrz0WmlymTnKNYhGT/mCPYpPVT+2XGtDeZ25Bl7VG4mj0n2YHCCBdc/tJdcoEJlgvhRLGMFVKfVNnfoY3fu1O7+77E6Koqj/RqIn6iyF7eqg0NzKDPUAF78RwBKzfKtbS87Y6fIkl120N38AAnM6gFRoPhN9W6dyoFZ/Wlq+Sp9G0m25a+DKtdflnOYiEfTw+FwuK6sch94xvhSxwMCYT740ZLJwaJviQ41O1klhAuUp77vLtahAuG+MluC8NEeU6mjiNfXBtrFT36fuC2adNVPa2MjAWsOZa6ZC+GXhoA/r/n/xchGY9UcXzIghoQcE6yd/qKX+i10RT2haq0=
  app: tinndarp-backend
  on:
    repo: breadoliveoilsalt/tinndarp-backend
    branch: master
