deploy:
  provider: heroku
  api_key:
    secure: EHyQ01TSfu5yc8zlYFZW4nvYFh4c8NqXDB4Qm7IWcP2meZWG2IY9lQS116zkfZrRk7WeTeMGhjBg/eybr0nyjQBTRAHQRgo/Y3cIGvWOR1w/LpbyBuC8yIzsGx6EM/tcecEYRAo+o2/L0hZsZs5400G3ByY+EAuoB8Cp64hoUuPo0V3UsNTgFsQXw5WncCCZSMLbcZn69B6FG00JdDqoN24CPYX40OG6hFq6O/FsBZSoDA+rRoEIigicNcAnT5WrEbceZO7TB4HWK1GLlwrKb8lW9OVYQB0NVL98R4lczyYfhnLbPCHrdawGc7KL7TiKtf6WLUEKftHGyEXUoJ3NzK4YFdVAr/+GiekIqYEd2/8Q0OyrXKAGWU0UQkzB6XoVXDJpOwJUSYJxHhgzSlj+nbnKC1N6zHRJ/WFoY1aTtI8gbr4694FkPEhNB64GL38X8Q2mezeASxJVRllE/R0TbA8SEhqWFhWPBer/C3W75a0wOAfrGYzyvbqPTaZ6m5JZAD8cxT2vQT29URTdNJNP56briTV6Pf9wu37j+OEIBKicGAoCZuK3c2lDCgrsQBqbWZKchwz0V8LsZYghjdNUJEsuFNbY6o8p4+wJuIf03ppsP1nfCYT4SzOiGUNU2wLZyPGoLAtZQAtd3ySerCgn5f1s/TZ0bvSkKziAXURclys=
  app: tinndarp-backend
  on:
    repo: breadoliveoilsalt/tinndarp-backend
